name: Update Gist with ISP Data

on:
  schedule:
    - cron: "0 0 * * *"  # 每天凌晨 00:00 UTC 执行
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download ISP data
        run: |
          curl -o all_cn.txt https://ispip.clang.cn/all_cn.txt
          curl -o all_cn_ipv6.txt https://ispip.clang.cn/all_cn_ipv6.txt

      - name: Update Gist
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          # 创建一个临时 JSON 文件
          cat > gist.json << EOF
          {
            "files": {
              "all_cn.txt": {
                "content": "$(cat all_cn.txt | sed 's/"/\\"/g')"
              },
              "all_cn_ipv6.txt": {
                "content": "$(cat all_cn_ipv6.txt | sed 's/"/\\"/g')"
              }
            }
          }
          EOF

          # 更新 Gist
          HTTP_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X PATCH \
            -H "Authorization: token $GIST_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/gists/$GIST_ID \
            -d @gist.json)

          # 检查响应状态
          if [ "$HTTP_RESPONSE" -ne 200 ]; then
            echo "Failed to update Gist, HTTP status: $HTTP_RESPONSE"
            exit 1
          fi

          echo "Gist updated successfully!"

      - name: Cleanup
        run: |
          rm -f all_cn.txt all_cn_ipv6.txt gist.json
