name: Update Gist with ISP Data

on:
  schedule:
    - cron: "0 0 * * *"  # 每天凌晨 00:00 UTC 执行
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Configure Git
        run: |
          git config --global core.eol lf
          git config --global core.autocrlf false
          
      - name: Download ISP data
        run: |
          curl --retry 3 --retry-delay 5 -f -o all_cn.txt https://ispip.clang.cn/all_cn.txt
          curl --retry 3 --retry-delay 5 -f -o all_cn_ipv6.txt https://ispip.clang.cn/all_cn_ipv6.txt
          
          # 验证文件是否下载成功
          if [ ! -s all_cn.txt ] || [ ! -s all_cn_ipv6.txt ]; then
            echo "Failed to download ISP data files"
            exit 1
          fi

      - name: Update Gist
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          jq -n --rawfile ipv4 all_cn.txt --rawfile ipv6 all_cn_ipv6.txt \
          '{"files": {"all_cn.txt": {"content": $ipv4}, "all_cn_ipv6.txt": {"content": $ipv6}}}' > gist.json
          
          RESPONSE=$(curl -sS -o response.json -w "%{http_code}" -X PATCH \
            -H "Authorization: Bearer $GIST_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            "https://api.github.com/gists/$GIST_ID" \
            -d @gist.json)

          if [ "$RESPONSE" -ne 200 ]; then
            echo "Error updating Gist. HTTP Status: $RESPONSE"
            cat response.json
            exit 1
          else
            echo "Gist updated successfully!"
          fi

      - name: Cleanup
        if: always()
        run: rm -f all_cn.txt all_cn_ipv6.txt gist.json response.json
