name: Update Gist with ISP Data

on:
  schedule:
    - cron: "0 0 * * *"  # 每天凌晨 00:00 UTC 执行
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download and process ISP data
        run: |
          curl -o all_cn.txt https://ispip.clang.cn/all_cn.txt
          sed 's/\(\d\{1,3\}\.\d\{1,3\}\.\d\{1,3\}\.\d\{1,3}\/\d\{1,2\}\)/\1\n/g' all_cn.txt > processed_all_cn.txt 
          curl -o all_cn_ipv6.txt https://ispip.clang.cn/all_cn_ipv6.txt 
          # Assuming all_cn_ipv6.txt also needs similar processing
          sed 's/\(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/\d{1,2}\)/\1\n/g' all_cn_ipv6.txt > processed_all_cn_ipv6.txt 

      - name: Update Gist
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          # 创建一个临时 JSON 文件
          cat > gist.json << EOF
          {
            "files": {
              "all_cn.txt": {
                "content": "$(cat processed_all_cn.txt)" 
              },
              "all_cn_ipv6.txt": {
                "content": "$(cat processed_all_cn_ipv6.txt)" 
              }
            }
          }
          EOF

          # 更新 Gist
          curl -s -o /dev/null -w "%{http_code}" -X PATCH \
            -H "Authorization: token $GIST_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/gists/$GIST_ID \
            -d @gist.json

      - name: Cleanup
        run: rm all_cn.txt all_cn_ipv6.txt processed_all_cn.txt processed_all_cn_ipv6.txt gist.json 
