name: Update Gist with ISP Data

on:
  schedule:
    - cron: "0 0 * * *" # 每天凌晨 00:00 UTC 执行
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch ISP data and update Gist
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          # Define variables
          ALL_CN_URL="https://ispip.clang.cn/all_cn.txt"
          ALL_CN_IPV6_URL="https://ispip.clang.cn/all_cn_ipv6.txt"
          ALL_CN_FILE="all_cn.txt"
          ALL_CN_IPV6_FILE="all_cn_ipv6.txt"

          # Download files
          for url in "$ALL_CN_URL" "$ALL_CN_IPV6_URL"; do
            file=$(basename "$url")
            if ! curl -o "$file" "$url"; then
              echo "Failed to download $file from $url"
              exit 1
            fi

            # Fix line breaks in downloaded files (ensure each IP has a newline)
            sed 's/\//\/\n/g' -i "$file" 
          done

          # ... (rest of the workflow)
