name: Update Gist with ISP Data

on:
  schedule:
    - cron: "0 0 * * *" # 每天凌晨 00:00 UTC 执行
  workflow_dispatch: # 手动触发

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch ISP data and update Gist
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          # 定义变量
          GIST_ID="1527b3cf050b36359e8fa320ac6a84d0"
          ALL_CN_URL="https://ispip.clang.cn/all_cn.txt"
          ALL_CN_IPV6_URL="https://ispip.clang.cn/all_cn_ipv6.txt"
          ALL_CN_FILE="all_cn.txt"
          ALL_CN_IPV6_FILE="all_cn_ipv6.txt"

          # 下载 all_cn.txt
          if ! curl -o "$ALL_CN_FILE" "$ALL_CN_URL"; then
            echo "Failed to download $ALL_CN_FILE from $ALL_CN_URL"
            exit 1
          fi

          # 下载 all_cn_ipv6.txt
          if ! curl -o "$ALL_CN_IPV6_FILE" "$ALL_CN_IPV6_URL"; then
            echo "Failed to download $ALL_CN_IPV6_FILE from $ALL_CN_IPV6_URL"
            exit 1
          fi

          # 构建 JSON 数据并更新 Gist
          JSON_DATA=$(cat <<EOF
{
  "files": {
    "all_cn.txt": {
      "content": "$(cat $ALL_CN_FILE | sed 's/"/\\"/g')"
    },
    "all_cn_ipv6.txt": {
      "content": "$(cat $ALL_CN_IPV6_FILE | sed 's/"/\\"/g')"
    }
  }
}
EOF
          )

          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X PATCH \
            -H "Authorization: token $GIST_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/gists/$GIST_ID \
            -d "$JSON_DATA")

          # 检查 API 请求返回状态
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Failed to update Gist, HTTP status: $RESPONSE"
            exit 1
          fi

          echo "Gist updated successfully!"
