name: Update Gist with ISP Data

on:
  schedule:
    - cron: "0 0 * * *" # 每天凌晨 00:00 UTC 执行
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch ISP data and update Gist
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          # 定义变量
          ALL_CN_URL="https://ispip.clang.cn/all_cn.txt"
          ALL_CN_IPV6_URL="https://ispip.clang.cn/all_cn_ipv6.txt"
          ALL_CN_FILE="all_cn.txt"
          ALL_CN_IPV6_FILE="all_cn_ipv6.txt"

          # 下载文件
          for url in "$ALL_CN_URL" "$ALL_CN_IPV6_URL"; do
            file=$(basename "$url")
            if ! curl -o "$file" "$url"; then
              echo "Failed to download $file from $url"
              exit 1
            fi
          done

          # 构建 JSON 数据并更新 Gist
          JSON_DATA=$(cat <<EOF
          {
            "files": {
              "all_cn.txt": {
                "content": "$(cat "$ALL_CN_FILE" | sed 's/"/\\"/g')"
              },
              "all_cn_ipv6.txt": {
                "content": "$(cat "$ALL_CN_IPV6_FILE" | sed 's/"/\\"/g')"
              }
            }
          }
          EOF
          )

          # 更新 Gist
          curl -s -o /dev/null -w "%{http_code}" -X PATCH \
            -H "Authorization: token $GIST_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/gists/$GIST_ID \
            -d "$JSON_DATA"
          echo $?  # 输出HTTP状态码
